import { Injector } from '@angular/core';
import { OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { UserInfo } from '@dongkap/do-core';
import { HttpBaseModel } from '@dongkap/do-core';
import { IndexedDBFactoryService } from '@dongkap/do-core';
import { BaseFormComponent, SelectParamModel } from '@dongkap/do-common';
import { AuthIndexedDBService } from '@dongkap/do-auth';
export declare class SystemPageComponent extends BaseFormComponent<any> implements OnInit {
    injector: Injector;
    private userService;
    private profileIndexedDB;
    private authIndexedDB;
    image: string;
    formGroupImage: FormGroup;
    uploadFinished: boolean;
    patternEmail: string;
    patternPhoneNumber: string;
    minLength: number;
    disabledUpload: boolean;
    provider: string;
    apiSelectCountry: HttpBaseModel;
    apiSelectProvince: HttpBaseModel;
    paramSelectProvince: SelectParamModel[];
    apiSelectCity: HttpBaseModel;
    paramSelectCity: SelectParamModel[];
    apiSelectDistrict: HttpBaseModel;
    paramSelectDistrict: SelectParamModel[];
    apiSelectSubDistrict: HttpBaseModel;
    paramSelectSubDistrict: SelectParamModel[];
    constructor(injector: Injector, userService: UserInfo, profileIndexedDB: IndexedDBFactoryService, authIndexedDB: AuthIndexedDBService);
    ngOnInit(): void;
    onInit(serviceName: string, apiName: string): void;
    onSelectCountry(select: any): void;
    onSelectProvince(select: any): void;
    onSelectCity(select: any): void;
    onSelectDistrict(select: any): void;
    onClearCountry(): void;
    onClearProvince(): void;
    onClearCity(): void;
    onClearDistrict(): void;
    uploadImage(file: any): void;
    valueSelect(prop: string): string;
    valueSelectNonLabel(prop: string): string;
    onSubmit(): void;
}
