import { Injector, EventEmitter } from '@angular/core';
import { ColumnMode, SelectionType, SortType } from '@swimlane/ngx-datatable';
import { Page, DatatableColumn } from '../../models/datatable.model';
export declare class DoDatatableBaseComponent {
    locale: string;
    injector: Injector;
    rows: any[];
    columns: DatatableColumn[];
    selected: any[];
    limit: number | undefined;
    count: number;
    offset: number;
    externalPaging: boolean;
    externalSorting: boolean;
    loadingIndicator: boolean;
    scrollbarH: boolean;
    scrollbarV: boolean;
    reorderable: boolean;
    sortType: SortType;
    messages: any;
    selectionType: SelectionType;
    columnMode: ColumnMode;
    headerHeight: any;
    footerHeight: any;
    rowHeight: number | 'auto' | ((row?: any) => number);
    header: boolean;
    column: boolean;
    footer: boolean;
    add: boolean;
    edit: boolean;
    delete: boolean;
    filter: boolean;
    startWithOpenData: boolean;
    page: EventEmitter<Page>;
    sort: EventEmitter<any>;
    select: EventEmitter<any>;
    activate: EventEmitter<any>;
    onButtonCell: EventEmitter<any>;
    constructor(locale: string, injector: Injector);
    setPage(page: Page): void;
    onSort(order: any): void;
    onSelect(selected: any): void;
    onActivate(event: any): void;
    sanitizedValue(value: any): any;
    stripHtml(html: string): string;
    onClickButton(event: any): void;
}
